---
  - name: Add Docker GPG key into apt
    apt_key:
      url: "{{ docker_key_url }}"
      state: present
    become: yes

  - name: Add Docker repository
    apt_repository:
      repo: "{{ docker_deb_url }}"
      filename: nodesource
      state: present
    become: yes

  - name: Install Docker packages
    apt:
      name: ['docker', 'docker-compose']
      update_cache: yes
      force: yes
      state: present
    become: yes

  - name: Install Docker Compose
    pip:
      name: ['docker', 'docker-compose']
      state: present
    become: yes

  - name: Adding current user Docker rights
    user:
      name: "{{ lookup('env','USER') }}"
      groups: docker
      append: yes
    become: yes